### ISSUE TITLE
no json data on varnish.discovery

### ISSUE THREAD

**Issue by forum77alive** [allenta/zabbix-template-for-varnish-cache#47]
root@zabbix:~# zabbix_get -s IP-agent -k varnish.discovery["","items"]
{
  "data": [
    {
      "{#LOCATION_ID}": "",
      "{#LOCATION}": ""
    }
  ]
}
root@zabbix:~# zabbix_get -s IP-agent -k varnish.discovery["","items"]
{
  "data": [
    {
      "{#LOCATION_ID}": "",
      "{#LOCATION}": ""
    }
  ]
}
root@zabbix:~# zabbix_get -s IP-agent -k varnish.discovery["","counters"]
{
  "data": []
}
root@zabbix:~# zabbix_get -s IP-agent-k varnish.discovery["","storages"]
{
  "data": [
    {
      "{#LOCATION_ID}": "",
      "{#LOCATION}": "",
      "{#SUBJECT_ID}": "SMA.Transient",
      "{#SUBJECT}": "SMA.Transient"
    },
    {
      "{#LOCATION_ID}": "",
      "{#LOCATION}": "",
      "{#SUBJECT_ID}": "SMA.s0",
      "{#SUBJECT}": "SMA.s0"
    }
  ]
}

**Comment by davidfb** [comment]
Those results seem pretty normal. You're invoking the script through _zabbix_get_ to make different discoveries.

Discovery of _items_ returns all known Varnish Cache instances, which will be always the current instance's name (in this case, an empty _LOCATION_ and _LOCATION_ID_ because the instance has the default name).

Discovery of _storages_ returns all configured storages for this Varnish Cache instance. In this case, it's the transient storage, and a malloc storage.

Discovery of _counters_ is returning an empty list because no custom counter has been incremented yet in this Varnish Cache instance.

Discovery is only one of the things the script gives support to, necessary for all item prototypes defined in the generated template. If you want to take a look at the stats to check it works, what you need is to invoke the script with it's _stats_ paremeter. Using _zabbix_get_:

`zabbix_get -s IP-agent -k varnish.stats[""]`

**Comment by forum77alive** [comment]
zabbix_get -s IP-agent -k varnish.stats[""] - working

I think discovery rules on my zabbix-server doesn't work, because items from Template App Varnish Cache was not created.
How can I fix/check this?

In old "Issues" you say we can added command in crontab:
 sudo /usr/local/bin/zabbix-varnish-cache.py -i '' send -c /etc/zabbix/zabbix_agentd.conf -s hostname
Now this is not actualy? It is not working to me
![zabbix inostudio net_ Latest data  refreshed every 30 sec  - Google Chrome 2019-12-17 19 13 30](https://user-images.githubusercontent.com/58973561/71013201-5bf9c180-2101-11ea-879f-87564fd307ad.png)

**Comment by carlosabalde** [comment]
I'm sorry but I'm afraid what you're reporting is not an issue with the template. You might be interested in [contacting Allenta](https://allenta.com/) for Zabbix professional services.
