### ISSUE TITLE
Send function removal

### ISSUE THREAD

**Issue by BennyEarl** [allenta/zabbix-template-for-varnish-cache#51]
Hi there,

Just wondering why the send function has been removed? and how I'm supposed to send the output over to zabbix?

I know I'm a bit behind the times with this question, but i've been using a version from years back to monitor varnish 4x and just got round to having a play with varnish 6.

Cheers,
Benny

**Comment by davidfb** [comment]
Hi Benny,

The script has changed in quite a few ways since then, indeed. Detailed usage is explained in the README. Basically, you have to add the varnish.discovery and varnish.stats user parameters to the Zabbix Agent configuration, like this:

`UserParameter=varnish.discovery[*],sudo /usr/local/bin/zabbix-varnish-cache.py -i '$1' discover $2`
`UserParameter=varnish.stats[*],sudo /usr/local/bin/zabbix-varnish-cache.py -i '$1' stats`

After applying the newest template (generated as, again, explained in the README) to the host, and as soon as necessary discoveries are run internally by Zabbix Server, data should start to reach the server.

You shouldn't get into any problem as it is pretty straightforward.

Cheers

**Comment by carlosabalde** [comment]
Reason for most of the changes David mentioned is stats are now embedded in a single active master item. Zabbix Sender is not used anymore.
