### ISSUE TITLE
Import error in 5.0.4

### ISSUE THREAD

**Issue by Maurotb** [allenta/zabbix-template-for-varnish-cache#52]
Hi, in 5.0.4 i have
Cannot read JSON: Syntax error.

**Comment by carlosabalde** [comment]
Could you please provide some more context about that error? If related with the template importation, you're probably doing some wrong because these templates are XML-based.

**Comment by Maurotb** [comment]
I have download template-app-varnish-cache.j2 (raw) and renamed to .json (wothout rename, zabbix not import)
When i import in template, zabbix give me only a generic "Cannot read JSON: Syntax error."
how can i help?

**Comment by carlosabalde** [comment]
The problem is the file you downloaded is not a JSON a file, that's why Zabbix is raising that error. As described in the instructions, that `.j2` file is a Jinja2 template used to generate several XML 'flavours' of the template. To keep this simple, what you need to do is to download a pregenerated XML template from [the releases page](https://github.com/allenta/zabbix-template-for-varnish-cache/releases/latest/) and follow the instructions in `README.md`.
