### ISSUE TITLE
Problems with execution

### ISSUE THREAD

**Issue by darz82** [allenta/zabbix-template-for-varnish-cache#53]
Hi, When I try to execute the python script I'm presented with the following error, can someone help? 

![image](https://user-images.githubusercontent.com/36069232/226477462-68f6fa7f-018b-4ad5-953d-7b8af7d30272.png)

**Comment by davidfb** [comment]
Hi @darz82 ,

Could you please execute the following commands and share their output?

`varnishd -V`
`varnishstat -1 -j -n "varnish_01"`

Thank you.

**Comment by darz82** [comment]
Hi @davidfb below are the extracts, anything else let me know, cheers.

`varnishd -V`
![image](https://user-images.githubusercontent.com/36069232/226598963-e1dbd78e-69c7-4d13-a9bc-0774d38a66eb.png)

` varnishstat -1 -j -n "varnish_01"` is 13000 plus lines as we have crap load of backends per varnish daemon, here's just a sample of that: 

{
  "version": 1,
  "timestamp": "2023-03-21T11:52:46",
  "counters": {
    "MGT.uptime": {
      "description": "Management process uptime",
      "flag": "c",
      "format": "d",
      "value": 3499
    },
    "MGT.child_start": {
      "description": "Child process started",
      "flag": "c",
      "format": "i",
      "value": 1
    },
    "MGT.child_exit": {
      "description": "Child process normal exit",
      "flag": "c",
      "format": "i",
      "value": 0
    },
    "MGT.child_stop": {
      "description": "Child process unexpected exit",
      "flag": "c",
      "format": "i",
      "value": 0
    },
    "MGT.child_died": {
      "description": "Child process died (signal)",
      "flag": "c",
      "format": "i",
      "value": 0
    },
    "MGT.child_dump": {
      "description": "Child process core dumped",
      "flag": "c",
      "format": "i",
      "value": 0
    },
    "MGT.child_panic": {
      "description": "Child process panic",
      "flag": "c",
      "format": "i",
      "value": 0
    },
    "MAIN.summs": {
      "description": "stat summ operations",
      "flag": "c",
      "format": "i",
      "value": 97956
    },
    "MAIN.uptime": {
      "description": "Child process uptime",
      "flag": "c",
      "format": "d",
      "value": 3500
    },
    "MAIN.sess_conn": {
      "description": "Sessions accepted",
      "flag": "c",
      "format": "i",
      "value": 468
    },
"VBE.boot.sitecore01.happy": {
      "description": "Happy health probes",
      "flag": "b",
      "format": "b",
      "value": 0
    },
    "VBE.boot.sitecore01.bereq_hdrbytes": {
      "description": "Request header bytes",
      "flag": "c",
      "format": "B",
      "value": 0
    },
    "VBE.boot.sitecore01.bereq_bodybytes": {
      "description": "Request body bytes",
      "flag": "c",
      "format": "B",
      "value": 0
    },
    "VBE.boot.sitecore01.beresp_hdrbytes": {
      "description": "Response header bytes",
      "flag": "c",
      "format": "B",
      "value": 0
    },
    "VBE.boot.sitecore01.beresp_bodybytes": {
      "description": "Response body bytes",
      "flag": "c",
      "format": "B",
      "value": 0
    },
    "VBE.boot.sitecore01.pipe_hdrbytes": {
      "description": "Pipe request header bytes",
      "flag": "c",
      "format": "B",
      "value": 0
    },
    "VBE.boot.sitecore01.pipe_out": {
      "description": "Piped bytes to backend",
      "flag": "c",
      "format": "B",
      "value": 0
    },
    "VBE.boot.sitecore01.pipe_in": {
      "description": "Piped bytes from backend",
      "flag": "c",
      "format": "B",
      "value": 0
    },
    "VBE.boot.sitecore01.conn": {
      "description": "Concurrent connections used",
      "flag": "g",
      "format": "i",
      "value": 0
    },
    "VBE.boot.sitecore01.req": {
      "description": "Backend requests sent",
      "flag": "c",
      "format": "i",
      "value": 0
    },
    "VBE.boot.sitecore01.unhealthy": {
      "description": "Fetches not attempted due to backend being unhealthy",
      "flag": "c",
      "format": "i",
      "value": 0
    },
    "VBE.boot.sitecore01.busy": {
      "description": "Fetches not attempted due to backend being busy",
      "flag": "c",
      "format": "i",
      "value": 0
    },
    "VBE.boot.sitecore01.fail": {
      "description": "Connections failed",
      "flag": "c",
      "format": "i",
      "value": 0
    },
    "VBE.boot.sitecore01.fail_eacces": {
      "description": "Connections failed with EACCES or EPERM",
      "flag": "c",
      "format": "i",
      "value": 0
    },
    "VBE.boot.sitecore01.fail_eaddrnotavail": {
      "description": "Connections failed with EADDRNOTAVAIL",
      "flag": "c",
      "format": "i",
      "value": 0
    },
    "VBE.boot.sitecore01.fail_econnrefused": {
      "description": "Connections failed with ECONNREFUSED",
      "flag": "c",
      "format": "i",
      "value": 0
    },
    "VBE.boot.sitecore01.fail_enetunreach": {
      "description": "Connections failed with ENETUNREACH",
      "flag": "c",
      "format": "i",
      "value": 0
    },
    "VBE.boot.sitecore01.fail_etimedout": {
      "description": "Connections failed ETIMEDOUT",
      "flag": "c",
      "format": "i",
      "value": 343
    },
    "VBE.boot.sitecore01.fail_other": {
      "description": "Connections failed for other reason",
      "flag": "c",
      "format": "i",
      "value": 0
    },
    "VBE.boot.sitecore01.helddown": {
      "description": "Connection opens not attempted",
      "flag": "c",
      "format": "i",
      "value": 0
    },

**Comment by davidfb** [comment]
Hi again @darz82,

Sadly, this template is only meant to be used with Varnish Cache Plus installations and yours are regular Varnish Cache instances, the open source flavor.

Anyway, both softwares are very similar for the purpose of this template, so you should be able to easily tweak the Python script in order to make it work if you want so. Maybe even create your own fork, as we don't offer support for open source Varnish Cache.

In case it is of any help, it seems that the problem you're facing comes from a change made in the output format for the varnishstat command (which is internally used by our script), included in Varnish Cache's 6.5 release (https://varnish-cache.org/docs/trunk/whats-new/upgrading-6.5.html#varnishstat). The script expects all counters to come on the first level of the JSON response when executing varnishstat, but from that version on, counters are returned inside a property called "counters", so if you just want a quick hack that works with your Varnish Cache version, you could apply the following change:

Change line 474:
`        for name, data in json.loads(output).items():`
For this:
`        for name, data in json.loads(output)['counters'].items():`

A proper implementation should check the value for the "version" property (or assume 0 as the version number if none is available) and extract the counters accordingly, but that's up to you on how you want to implement it :smile:
