### ISSUE TITLE
python script exception

### ISSUE THREAD

**Issue by Jefl** [allenta/zabbix-template-for-varnish-cache#6]
Hi there !
Trying to run /usr/local/bin/zabbix-varnish-cache.py ,
I got the following error:
`/usr/local/bin/zabbix-varnish-cache.py`
`   File "/usr/local/bin/zabbix-varnish-cache.py", line 239`
`    for key, value in result.items()`
`      ^`
`SyntaxError: invalid syntax`

I'm running python 2.3 on centos 6.4

**Comment by davidfb** [comment]
Hi @Jefl,

Seems like your having a problem with a dict comprehension. This functionality is only available since Python 2.7, so if you're using Python 2.3 it's not going to work. Yo may try to change the dict comprehension for a dict initialization passing an iterable, basically changing lines from 237 to 241:

`return {key: value for key, value in result.items() if value['value'] is not None}`

for:

`return dict((key, value) for key, value in result.items() if value['value'] is not None)`

Anyway, the recommendation is, if possible, for you to upgrade your Python installation to version 2.7.
